# Generated by Django 5.2.7 on 2025-12-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mock_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mocktest',
            options={'ordering': ['-created_at']},
        ),
    ]
