# Generated by Django 5.2.8 on 2025-11-18 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('subject', models.CharField(choices=[('math', 'Matematika'), ('physics', 'Fizika'), ('chemistry', 'Kimyo'), ('biology', 'Biologiya'), ('history', 'Tarix'), ('literature', 'Adabiyot'), ('english', 'Ingliz tili'), ('russian', 'Rus tili'), ('it', 'Informatika'), ('other', 'Boshqa')], max_length=50, verbose_name='Fan')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Sinf')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video fayl')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Thumbnail')),
                ('duration', models.IntegerField(default=0, verbose_name='Davomiyligi (sekund)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar")),
                ('likes', models.IntegerField(default=0, verbose_name='Likelar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Video dars',
                'verbose_name_plural': 'Video darslar',
                'ordering': ['-created_at'],
            },
        ),
    ]
