# Generated by Django 5.2.8 on 2025-11-18 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateTimeField(verbose_name='Dars sanasi')),
                ('subject', models.CharField(max_length=100, verbose_name='Fan')),
                ('grade', models.IntegerField(verbose_name='Sinf')),
                ('topic', models.CharField(max_length=300, verbose_name='Mavzu')),
                ('lesson_type', models.CharField(choices=[('new', 'Yangi mavzu'), ('practice', 'Mashq darsi'), ('review', 'Takrorlash'), ('exam', 'Nazorat')], default='new', max_length=50, verbose_name='Dars turi')),
                ('methodology_rating', models.IntegerField(choices=[(5, "A'lo (5)"), (4, 'Yaxshi (4)'), (3, 'Qoniqarli (3)'), (2, 'Qoniqarsiz (2)'), (1, 'Yomon (1)')], verbose_name='Metodika (5 ball)')),
                ('material_mastery', models.IntegerField(choices=[(5, "A'lo (5)"), (4, 'Yaxshi (4)'), (3, 'Qoniqarli (3)'), (2, 'Qoniqarsiz (2)'), (1, 'Yomon (1)')], verbose_name='Materialni egallash (5 ball)')),
                ('student_engagement', models.IntegerField(choices=[(5, "A'lo (5)"), (4, 'Yaxshi (4)'), (3, 'Qoniqarli (3)'), (2, 'Qoniqarsiz (2)'), (1, 'Yomon (1)')], verbose_name="O'quvchilar faolligi (5 ball)")),
                ('time_management', models.IntegerField(choices=[(5, "A'lo (5)"), (4, 'Yaxshi (4)'), (3, 'Qoniqarli (3)'), (2, 'Qoniqarsiz (2)'), (1, 'Yomon (1)')], verbose_name='Vaqtni taqsimlash (5 ball)')),
                ('technology_use', models.IntegerField(choices=[(5, "A'lo (5)"), (4, 'Yaxshi (4)'), (3, 'Qoniqarli (3)'), (2, 'Qoniqarsiz (2)'), (1, 'Yomon (1)')], verbose_name="Texnologiya qo'llash (5 ball)")),
                ('achievements', models.TextField(verbose_name='Yutuqlar va ijobiy tomonlar')),
                ('weaknesses', models.TextField(verbose_name='Kamchiliklar')),
                ('recommendations', models.TextField(verbose_name='Tavsiyalar va takliflar')),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Umumiy baho')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending', 'Tasdiq kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='draft', max_length=20, verbose_name='Holat')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rad etish sababi')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha izohlar")),
                ('attachments', models.FileField(blank=True, null=True, upload_to='lesson_analysis/', verbose_name='Biriktirmalar (rasm, video)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_given', to='teachers.teacher', verbose_name='Tahlilchi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_received', to='teachers.teacher', verbose_name="Dars o'tgan o'qituvchi")),
            ],
            options={
                'verbose_name': 'Dars tahlili',
                'verbose_name_plural': 'Dars tahliллари',
                'ordering': ['-lesson_date'],
            },
        ),
        migrations.CreateModel(
            name='LessonAnalysisComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lesson_analysis.lessonanalysis', verbose_name='Tahlil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['created_at'],
            },
        ),
    ]
