# Generated by Django 5.2.7 on 2025-12-19 12:17

from django.db import migrations
from django.contrib.auth.hashers import make_password


def reset_superadmin_password(apps, schema_editor):
    User = apps.get_model('users', 'User')

    # Admin superadmin ni topish yoki yaratish
    user, created = User.objects.get_or_create(
        username='Admin',
        defaults={
            'email': 'admin@example.com',
            'role': 'superadmin',
            'is_staff': True,
            'is_superuser': True,
        }
    )

    # Parolni o'rnatish (make_password bilan)
    user.password = make_password('admin123')
    user.role = 'superadmin'
    user.is_staff = True
    user.is_superuser = True
    user.save()


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.RunPython(reset_superadmin_password, reverse_migration),
    ]
