# Generated by Django 5.2.7 on 2025-12-19

from django.db import migrations
from django.contrib.auth.hashers import make_password


def reset_superadmin_password(apps, schema_editor):
    User = apps.get_model('users', 'User')

    # Barcha superadminlarni topish
    superadmins = User.objects.filter(role='superadmin')

    if superadmins.exists():
        # Mavjud superadminlarning parolini yangilash
        for user in superadmins:
            user.password = make_password('admin123')
            user.is_staff = True
            user.is_superuser = True
            user.save()
            print(f"Superadmin yangilandi: {user.username}")
    else:
        # Yangi superadmin yaratish
        User.objects.create(
            username='Admin',
            email='admin@example.com',
            password=make_password('admin123'),
            role='superadmin',
            is_staff=True,
            is_superuser=True,
        )
        print("Yangi superadmin yaratildi: Admin")


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_reset_superadmin_password'),
    ]

    operations = [
        migrations.RunPython(reset_superadmin_password, reverse_migration),
    ]
