# Generated by Django 5.2.8 on 2025-11-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('subject', models.CharField(choices=[('math', 'Matematika'), ('physics', 'Fizika'), ('chemistry', 'Kimyo'), ('biology', 'Biologiya'), ('history', 'Tarix'), ('literature', 'Adabiyot'), ('english', 'Ingliz tili'), ('russian', 'Rus tili'), ('it', 'Informatika'), ('other', 'Boshqa')], max_length=50, verbose_name='Fan')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Sinf')),
                ('file', models.FileField(upload_to='materials/', verbose_name='Fayl')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar")),
                ('downloads', models.IntegerField(default=0, verbose_name='Yuklab olishlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
                'ordering': ['-created_at'],
            },
        ),
    ]
