# Generated by Django 5.2.8 on 2025-12-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='subject',
            field=models.CharField(choices=[('math', 'Matematika'), ('physics', 'Fizika'), ('chemistry', 'Kimyo'), ('biology', 'Biologiya'), ('history', 'Tarix'), ('literature', 'Adabiyot'), ('english', 'Ingliz tili'), ('russian', 'Rus tili'), ('informatics', 'Informatika'), ('other', 'Boshqa')], max_length=50, verbose_name='Fan'),
        ),
    ]
