# Generated by Django 5.2.8 on 2025-12-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_material_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(max_length=255, upload_to='materials/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='material',
            name='grade',
            field=models.IntegerField(default=1, verbose_name='Sinf'),
        ),
        migrations.AlterField(
            model_name='material',
            name='subject',
            field=models.CharField(choices=[('math', 'Matematika'), ('physics', 'Fizika'), ('chemistry', 'Kimyo'), ('biology', 'Biologiya'), ('informatics', 'Informatika'), ('english', 'Ingliz tili'), ('uzbek', "O'zbek tili"), ('russian', 'Rus tili'), ('history', 'Tarix'), ('geography', 'Geografiya'), ('literature', 'Adabiyot'), ('sport', 'Jismoniy tarbiya'), ('other', 'Boshqa')], max_length=50, verbose_name='Fan'),
        ),
    ]
