# Generated by Django 5.2.8 on 2025-11-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Oy')),
                ('total_points', models.IntegerField(default=0, verbose_name='Jami ball')),
                ('rank', models.IntegerField(default=0, verbose_name="O'rin")),
                ('teachers_count', models.IntegerField(default=0, verbose_name="O'qituvchilar soni")),
            ],
            options={
                'verbose_name': 'Maktab reytingi',
                'verbose_name_plural': 'Maktablar reytingi',
                'ordering': ['-month', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='TeacherRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Oy')),
                ('total_points', models.IntegerField(default=0, verbose_name='Jami ball')),
                ('rank', models.IntegerField(default=0, verbose_name="O'rin")),
            ],
            options={
                'verbose_name': "O'qituvchi reytingi",
                'verbose_name_plural': "O'qituvchilar reytingi",
                'ordering': ['-month', 'rank'],
            },
        ),
    ]
