# Generated by Django 5.2.8 on 2025-11-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('scheduled_at', models.DateTimeField(verbose_name='Rejalashtirilgan vaqt')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi'), ('completed', 'Yakunlandi')], default='pending', max_length=20, verbose_name='Holat')),
                ('notes', models.TextField(blank=True, verbose_name='Eslatmalar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Maslahat',
                'verbose_name_plural': 'Maslahatlar',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
