# Generated by Django 5.2.8 on 2025-11-18 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_student', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_mentor', to='teachers.teacher'),
        ),
    ]
