# Generated by Django 5.2.7 on 2025-12-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='consultation_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=20, verbose_name='Turi'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='duration',
            field=models.PositiveIntegerField(default=60, verbose_name='Davomiyligi (daqiqa)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='meeting_url',
            field=models.URLField(blank=True, verbose_name='Uchrashuv havolasi'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
    ]
