# Generated by Django 5.2.8 on 2025-11-18 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('material', 'Material'), ('video', 'Video dars'), ('consultation', 'Maslahat'), ('training', 'Trening'), ('other', 'Boshqa')], max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('points', models.IntegerField(default=0, verbose_name='Ball')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Faoliyat',
                'verbose_name_plural': 'Faoliyatlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'Matematika'), ('physics', 'Fizika'), ('chemistry', 'Kimyo'), ('biology', 'Biologiya'), ('history', 'Tarix'), ('literature', 'Adabiyot'), ('english', 'Ingliz tili'), ('russian', 'Rus tili'), ('it', 'Informatika'), ('other', 'Boshqa')], max_length=50, verbose_name='Fan')),
                ('level', models.CharField(choices=[('teacher', "O'qituvchi"), ('assistant', 'Assistant'), ('expert', 'Expert')], default='teacher', max_length=20, verbose_name='Daraja')),
                ('total_points', models.IntegerField(default=0, verbose_name='Jami ball')),
                ('monthly_points', models.IntegerField(default=0, verbose_name='Oylik ball')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schools.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['-total_points'],
            },
        ),
    ]
