# Generated by Django 5.2.7 on 2025-12-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('math', 'Matematika'), ('physics', 'Fizika'), ('chemistry', 'Kimyo'), ('biology', 'Biologiya'), ('history', 'Tarix'), ('geography', 'Geografiya'), ('literature', 'Adabiyot'), ('uzbek', "O'zbek tili"), ('english', 'Ingliz tili'), ('russian', 'Rus tili'), ('informatics', 'Informatika'), ('pedagogy', 'Pedagogika'), ('psychology', 'Psixologiya'), ('other', 'Boshqa')], max_length=50, verbose_name='Fan'),
        ),
    ]
