# Generated by Django 5.2.8 on 2025-11-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('response', models.TextField(verbose_name='Javob')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Suhbat tarixi',
                'verbose_name_plural': 'Suhbat tarixi',
                'ordering': ['-created_at'],
            },
        ),
    ]
